function chans = bv_getNEOChannels()

chans = {'EEG Fp2-C4', 'EEG C4-O2', 'EEG Fp1-C3', 'EEG C3-O1', ...
    'EEG Fp2-T8', 'EEG T8-O2', 'EEG Fp1-T7', 'EEG T7-O1', 'EEG A2-T8', ...
    'EEG T8-C4', 'EEG C4-Cz', 'EEG Cz-C3', 'EEG C3-T7', 'EEG T7-A1', ...
    'EEG Fp2-Cz', 'EEG Cz-O2', 'EEG Fp1-Cz', 'EEG Cz-O1', 'EEG Fp2-EOGV'};
